# Generated by Django 5.0.5 on 2024-06-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_category_alter_product_subcategory'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subcategory',
            name='unique_subcategory_per_category',
        ),
    ]
